<?php

namespace Bacardi55\CvgeneratorBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Bacardi55\CvgeneratorBundle\Entity\Cv;

/**
 * CvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository{
}
