<?php

namespace Bacardi55\CvgeneratorBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Bacardi55\CvgeneratorBundle\Entity\Cv;
use Bacardi55\CvgeneratorBundle\Repository\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvRepository extends EntityRepository
{
/*
  public function getCv($id){
    $cv = new Cv();
    if(!$id)
      return $cv;

    //$cvs = $this->getDoctrine()->getRepository('Bacardi55CvgeneratorBundle:Cv')->findAll();
    $query = $this->getEntityManager()->createQuery('SELECT c, ca, el
      FROM Bacardi55CvgeneratorBundle:Cv c
        LEFT JOIN c.categories ca
        LEFT JOIN ca.elements el
      WHERE c.id = :id
        AND ca.parentCategory IS NULL
    ')->setParameter('id', $id);

    try {
      $cv = $query->getSingleResult();

      // Get All Sub Category
      $categories = $cv->getCategories();
      $parent_cat_ids = array();
      foreach($categories as $category){
        $parent_cat_ids[] = $category->getId();
      }

      $query = $this->getEntityManager()->createQuery(
        'SELECT sc 
          FROM Bacardi55CvgeneratorBundle:Category sc
          WHERE sc.id IN (:ids)'
      )->setParameter('ids', $parent_cat_ids);

      $results = $query->getResult();
      echo '<pre>';
      print_r($results);die;
 
      return $cv;
    } catch (\Doctrine\ORM\NoResultException $e) {
      return null;
    }
  }
*/


}
