<?php

namespace Bacardi55\CvgeneratorBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvRepository extends EntityRepository
{
}