<?php

namespace Bacardi55\CvgeneratorBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Bacardi55\CvgeneratorBundle\Entity\Element;

/**
 * ElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementRepository extends EntityRepository{
}
