Bacardi55CvgeneratorBundle_homepage:
  pattern:  /cv
  defaults: { _controller: Bacardi55CvgeneratorBundle:Cv:index }

Bacardi55CvgeneratorBundle_cv:
  pattern: /cv/{id}
  defaults: { _controller: Bacardi55CvgeneratorBundle:Cv:see }
